### ISSUE TITLE
what clang dir?, there is like 4

### ISSUE THREAD

**Issue by Chococatpp** [eebssk1/aosp-enable-polly#1]
the title says it all

**Comment by eebssk1** [comment]
Hmm...

You can check which clang binary is used by using ps or htop when building.

I have not compile android rom now so I can not help you more.

**Comment by eebssk1** [comment]
If you are not sure then you can just deploy the wrappers in every clang version directory anyway.

The build system may also use different clang version when building some projects BTW.

**Comment by Chococatpp** [comment]
> Hmm...
> 
> You can check which clang binary is used by using ps or htop when building.
> 
> I have not compile android rom now so I can not help you more.

nvm i found it in my global.go the default clang folder for almost every project. it was 60mb stiped from the original build and 10mb more for build a user build, thanks for the script!

**Comment by eebssk1** [comment]
> > Hmm...
> > You can check which clang binary is used by using ps or htop when building.
> > I have not compile android rom now so I can not help you more.
> 
> nvm i found it in my global.go the default clang folder for almost every project. it was 60mb stiped from the original build and 10mb more for build a user build, thanks for the script!

You shoud modify the script to only enable polly when project that you selected enable it with some commandline define.
Enable it globally might break some components in somewhere that hard to notice.

**Comment by Chococatpp** [comment]
> > > Hmm...
> > > You can check which clang binary is used by using ps or htop when building.
> > > I have not compile android rom now so I can not help you more.
> > 
> > 
> > nvm i found it in my global.go the default clang folder for almost every project. it was 60mb stiped from the original build and 10mb more for build a user build, thanks for the script!
> 
> You shoud modify the script to only enable polly when project that you selected enable it with some commandline define. Enable it globally might break some components in somewhere that hard to notice.

it broke my boot img but its fine. after replaced it with a old one worked
